name: NextJS Build as Export

on:
  push:
    branch:
      -master

Jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@4.0.2
        with:
          node-version: '20'
          #cache: 'npm'
          #cache-dependency-path: './node_modules'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install
      
      - name: Build
       run: npm run build

      - name: Verify the output folder
        run: ls -l out

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app build package
          path: out

      - name: Install netlify CLI
        run: npm install -g netlify-cli

      - name: deploy to netlify
        run: |
          netlify deploy --prod \
            --dir=out \
            --site ${{ secrets.NETLIFY_SITE_ID}} \
            --auth ${{ secrects.NETLIFY_API_TOKEN}}





