# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: nextJS pipeline

on:
  push:
    branches:
      -master

jobs:
  job1:
    name: My Job1
    runs-on: ubuntu-latest
    steps: 
      -name: First step -job1
      run: echo "First Step in job1"

      -name: create a file -job1
      run: touch test.txt

  job2:
    -name: My Job2    
    runs-on: ubuntu-latest
    steps: 
      -name: verify the file - job2
      run: ls -1